#!/bin/sh

if [ $# != 1 ]; then
    echo "Usage: $(basename "$0") <day-number>" >&2
    exit 1
fi

if [ ${PWD##*/} != "2021" ]; then
    echo "must be run from root of 2021 directory in aoc repository" >&2
    exit 1
fi



name="$(printf "aoc%02d" "$1")"
cp -r .template "$name"
